### ISSUE TITLE
Autogenerate copyright year

### ISSUE THREAD

**Issue by MyNameIsMikeGreen** [MyNameIsMikeGreen/platypus#20]
Currently, the copyright statement at the bottom of all pages is hardcoded. Make this dynamic such that the end year is the current year.

e.g:

- If it were 2024, the copyright statement would read `© Copyright 2020-2024 Mike Green`
- If it were 2025, the copyright statement would read `© Copyright 2020-2025 Mike Green`

The code should not need to be updated manually each year.

**Comment by Kumar85** [comment]
Not that hard with JavaScript. You can use the native JavaScript Date object for that.
Example:

HTML code :
 `<h4>© Copyright 2020-<span id="currentYear"></span> Mike Green</h4>`

JavaScript code :
`let copyrightSpan = document.getElementById("currentYear")`
`copyrightSpan.innerText = (new Date()).getFullYear()`

or if you're using jQuery :
`$("#currentYear").text((new Date()).getFullYear())`


Good Luck with your project  👍

**Comment by cxxiii** [comment]
I submitted a PR

**Comment by MyNameIsMikeGreen** [comment]
Thank you both for your input. This feature has now been merged into master and is deployed to the site.
